name: keycloak-client-login-policy

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    restart: unless-stopped
    depends_on:
      - postgres
    command:
      - start-dev
      - --import-realm
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8787:8787"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_LOG_LEVEL: info,de.verdigado:debug
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
    volumes:
      - ./providers:/opt/keycloak/providers
      - ./import:/opt/keycloak/data/import
